name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - documentation
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
  copy_to_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Copy svg
        run: mv diagram.svg ./static/img
