name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - documentation
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
      - name: Move diagram
        run: mv diagram.svg ./static/img
      - name: copy file
        uses: canastro/copy-file-action@master
          with:
            source: "diagram.svg"
            target: "./static/img"
